language: go
sudo: false
services:
  - docker
matrix:
  include:
    - go: 1.8
    - go: 1.9
    - go: 1.x
    - go: master
  allow_failures:
    - go: master

  script:
    - go vet .
    - go test
    - ls -al